export const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA';
export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const OPEN_EACH_PRODUCT = 'OPEN_EACH_PRODUCT';
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS';
export const GET_PRODUCT_WITH_ID = 'GET_PRODUCT_WITH_ID';
